### ISSUE TITLE
Add a note on avoiding colons on consumer group names to ensure lag metrics work properly

### ISSUE THREAD

**Issue by millenc** [awsdocs/amazon-msk-developer-guide#5]
If a consumer group name contains colons (`:`) the consumer lag metrics for that group are not properly exported to Prometheus (and Cloudwatch I think). This has happened to me because I was configuring the consumer group name of a Lambda source mapping to be the ARN of the target function (something like `arn:aws:lambda:eu-west-1:012345678901:function:my-lambda-function`). I've been able to detect the cause with the help of the support team (thanks!).

I haven't found any reference on the docs about this caveat and I'm not event sure if it's only the colon that causes issues or other special characters as well. Anyhow, I think it would be nice to add a note to the docs warning users to not use colons here:

https://docs.aws.amazon.com/msk/latest/developerguide/consumer-lag.html

or here as a common pitfall:

https://docs.aws.amazon.com/msk/latest/developerguide/troubleshooting.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
